### ISSUE TITLE
Impl `{Upper,Lower}Hex` for `Paint`

### ISSUE THREAD

**Issue by eignnx** [SergioBenitez/yansi#41]
I wish I could color my value like this:

```rust
use yansi::Paint;
println!("address = {:04X}", Paint::yellow(0x0000BEEF));
```

But I get this error:

```
error[E0277]: the trait bound `Paint<{integer}>: UpperHex` is not satisfied
   --> src\cpu.rs:222:38
    |
222 |         println!("address = {:04X}", Paint::yellow(0x0000BEEF));
    |                             ------   ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `UpperHex` is not implemented for `Paint<{integer}>`
    |                             |
    |                             required by a bound introduced by this call
    |
    = help: the following other types implement trait `UpperHex`:
              &T
              &mut T
              BitArray<A, O>
              BitBox<T, O>
              BitVec<T, O>
              Domain<'a, Const, T, O>
              NonZeroI128
              NonZeroI16
            and 36 others
note: required by a bound in `ArgumentV1::<'a>::new_upper_hex`
   --> C:\<REDACTED>\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\fmt\mod.rs:356:5
    |
356 |     arg_new!(new_upper_hex, UpperHex);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `ArgumentV1::<'a>::new_upper_hex`
    = note: this error originates in the macro `$crate::format_args_nl` which comes from the expansion of the macro `arg_new` (in Nightly builds, run with -Z 
macro-backtrace for more info)
```

Currently I have to do this:

```rust
println!("address = {}", Paint::yellow(format!("{:04x}", 0x0000BEEF)));
```

But this requires allocating a `String`.

**Comment by SergioBenitez** [comment]
This works perfectly with yansi 1.0:

```rust
use yansi::Paint;

fn main() {
    println!("address = {:08X}", 0x0000BEEF.yellow());
}

// address = 0000BEEF
```
